ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
#for media url
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('meriemecomsite/', admin.site.urls),
    path('',include('store.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views


urlpatterns=[

path('<int:cat>',views.store,name='store'),
path('<int:cat>/<int:subcat>/',views.store2,name='store2'),
path('<int:pk>/description/',views.slider,name='slider'),
path('cart/',views.cart,name='cart'),
path('checkout/',views.checkout,name='checkout'),
path('update_item/',views.updateItem,name='update_item'),
path('process_order/',views.processOrder,name='process_order'),
path('signup/', views.signup_view,name='signup'),
path('login/', views.login_view,name='login'),
path('logout/', views.logout_view,name='logout'),



]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from datetime import datetime, timedelta
from django.db.models import Sum

class Color(models.Model):
    name=models.CharField(max_length=200,null=True)
    def __str__(self):
        return self.name

class Size(models.Model):
    name=models.CharField(max_length=200,null=True)
    def __str__(self):
        return self.name

class Category(models.Model):
    name=models.CharField(max_length=200,null=True)
    def __str__(self):
        return self.name

class SubCategory(models.Model):
    name=models.CharField(max_length=200,null=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE,null=True,blank=False)
    def __str__(self):
        return self.name

class Customer(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,null=True,blank=True)
    name=models.CharField(max_length=200,null=True)
    email=models.CharField(max_length=200,null=True)

    def __str__(self):
        return self.name



class Product(models.Model):
    name=models.CharField(max_length=200,null=True)
    color=models.ManyToManyField(Color,blank=True,through='TakenColorSize')
    size=models.ManyToManyField(Size,blank=True,through='TakenColorSize')
    price=models.DecimalField(max_digits=5,decimal_places=2)
    digital=models.BooleanField(default=False,null=True,blank=False)
    category=models.ForeignKey(Category,on_delete=models.CASCADE,null=True,blank=False)
    sub_category=models.ForeignKey(SubCategory,on_delete=models.CASCADE,null=True,blank=False)
    description = models.TextField(null=True,blank=True)
    featured = models.ImageField(null=True)
    GENDER_CHOICES = (
    ('none', 'none'),
    ('man', 'man'),
    ('woman', 'woman'),
    ('kids', 'kids')  )# yeah that's not a gender but you could want to have this
    gender = models.CharField(max_length=30, choices=GENDER_CHOICES,null=True,blank=True)

    def __str__(self):
        return self.name
    @property
    def imageURL(self):
        try:
            url = self.featured.url
        except:
            url = ''
        print('URL:', url)
        return url

class TakenColorSize(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE,blank=True,null=True)
    size = models.ForeignKey(Size, on_delete=models.CASCADE,blank=True,null=True)
    def __str__(self):
        return str(self.id)




class Image(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	name = models.CharField(max_length=200)
	image = models.ImageField()

	def __str__(self):
		return self.name

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		print('URL:', url)
		return url

class Order(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.SET_NULL,null=True,blank=False)
    date=models.DateTimeField(auto_now_add=True)
    complete=models.BooleanField(default=False,null=True,blank=False)
    transaction_id=models.CharField(max_length=200,null=True)

    def __str__(self):
        return str(self.id)
    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping


    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total



class OrderItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE,null=True,blank=False)
    order=models.ForeignKey(Order,on_delete=models.SET_NULL,null=True,blank=False)
    quantity=models.IntegerField(default=0,null=True,blank=False)
    date_added=models.DateTimeField(auto_now_add=True)
    color_size = models.ForeignKey(TakenColorSize, on_delete=models.CASCADE,blank=True,null=True)

    def __str__(self):
        return str(self.id)
    @property
    def get_total(self):
        return self.quantity*self.product.price


class ShippingAddress(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.SET_NULL,null=True,blank=False)
    order=models.ForeignKey(Order,on_delete=models.SET_NULL,null=True,blank=False)
    address=models.CharField(max_length=200,null=True)
    city=models.CharField(max_length=200,null=True)
    state=models.CharField(max_length=200,null=True)
    zipcode=models.CharField(max_length=200,null=True)
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.address)

store/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.contrib.auth.models import User
from . import models

class CostumerForm(UserCreationForm):
    name=forms.CharField(max_length=50)
    email = forms.EmailField(max_length=70)
    class Meta(UserCreationForm.Meta):
        model = User
    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.save()
        costumer = models.Customer.objects.create(user=user)
        costumer.name=self.cleaned_data.get('name')
        costumer.email=self.cleaned_data.get('email')
        costumer.save()
        return user

store/views.py
from django.http import JsonResponse
import json
import datetime
from .models import *
from .utils import cookieCart,cartData,guestOrder
from django.shortcuts import render,redirect
from . import forms
from django.contrib.auth import login,logout
from django.urls import reverse
from django.contrib.auth.forms import AuthenticationForm



"""
You specified order_item.quantity += 1, This is okay until 2 people click "Add to cart"
at the same time or a user clicks very fast that the first request isn't finished,
This is a race condition and should be avoided. Like this
from django.db.models import F
order_item.quantity = F('quantity') + 1

email field
"""


def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect(reverse('store', kwargs={"cat":0}))


def signup_view(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    categories=Category.objects.all()
    product = Product.objects.all()
    if request.method=='POST':
        #getting the passed values in the request and putting them in a new form
        #to check if it is valid or nop
        form=forms.CostumerForm(request.POST)
        if form.is_valid():
            #save user in database plus
            #log user in after signinup....
            user=form.save()
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            login(request,user)
            #app name plus the name of the url in the view
            return redirect(reverse('store', kwargs={"cat":0}))
        else:
            form=forms.CostumerForm()
            return render(request, 'store/signup.html', { 'form': form,'context':context})
    #if method is get then send the forms
    #if the form is not valid it ll resend the form also
    else:
        #instanciate a form
        form=forms.CostumerForm()
    #send the form the the html template
    context = {'form': form,'product':product, 'cartItems':cartItems,'categories':categories}
    return  render(request, 'store/signup.html', context)

def login_view(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    categories=Category.objects.all()
    product = Product.objects.all()
    print(cartItems)
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            #redirect user to login
            user = form.get_user()
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            login(request,user)
            #check where the user was trying to go with the next value in the url
            if 'next' in request.POST:
                #'next' is the name of the input in the html
                return redirect(request.POST.get('next'))
            else:
                return redirect(reverse('store', kwargs={"cat":0}))
    else:
        form=AuthenticationForm()
    context = {'form':form,'product':product, 'cartItems':cartItems,'categories':categories}
    return render(request,'store/login.html',context)

def slider(request,pk):
	data = cartData(request)
	cartItems = data['cartItems']
	order = data['order']
	items = data['items']
	product = Product.objects.get(id=pk)
	categories=Category.objects.all()
	context = {'product':product, 'cartItems':cartItems,'categories':categories}
	return render(request, 'store/slider.html', context)

def store(request,cat):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    products = Product.objects.filter(category=cat)
    #if category doesnt exits then show all products
    cat = Category.objects.filter(id=cat).count()
    if cat == 0:
        products=Product.objects.all()
    categories=Category.objects.all()
    context = {'products':products, 'cartItems':cartItems,'categories':categories}
    return render(request, 'store/store.html', context)

def store2(request,cat,subcat):
	data = cartData(request)
	cartItems = data['cartItems']
	order = data['order']
	items = data['items']
	products = Product.objects.filter(category=cat,sub_category=subcat)
	#if category doesnt exits then show all products
	cat = Category.objects.filter(id=cat).count()
	subcat =SubCategory.objects.filter(id=subcat).count()
	if cat == 0 or subcat == 0:
		products=Product.objects.all()
	categories=Category.objects.all()
	context = {'products':products, 'cartItems':cartItems,'categories':categories}
	return render(request, 'store/store.html', context)



def cart(request):
	data = cartData(request)
	cartItems = data['cartItems']
	order = data['order']
	items = data['items']

	categories=Category.objects.all()


	context = {'items':items, 'order':order, 'cartItems':cartItems,'categories':categories}
	return render(request, 'store/cart.html', context)

def checkout(request):
	data = cartData(request)
	cartItems = data['cartItems']
	order = data['order']
	items = data['items']
	categories=Category.objects.all()


	context = {'items':items, 'order':order, 'cartItems':cartItems,'categories':categories}
	return render(request, 'store/checkout.html', context)

def updateItem(request):
	data = json.loads(request.body)
	productId = data['productId']
	action = data['action']
	val=data['val']
	colorsize=data['colorsize']
	print('Action:', action)
	print('Product:', productId)
	customer = request.user.customer
	product = Product.objects.get(id=productId)
	tcolorsize = TakenColorSize.objects.get(id=colorsize)

	order, created = Order.objects.get_or_create(customer=customer, complete=False)
	#here add color size
	orderItem, created = OrderItem.objects.get_or_create(order=order, product=product,color_size=tcolorsize)
	if action == 'add':
		orderItem.quantity = (orderItem.quantity + int(val))
	elif action == 'remove':
		orderItem.quantity = (orderItem.quantity - 1)
	orderItem.save()
	if orderItem.quantity <= 0:
		orderItem.delete()
	return JsonResponse('Item was added', safe=False)




def processOrder(request):
	transaction_id = datetime.now().timestamp()
	data = json.loads(request.body)
	if request.user.is_authenticated:
		customer = request.user.customer
		order, created = Order.objects.get_or_create(customer=customer, complete=False)
	else:
		customer, order = guestOrder(request, data)

	total = float(data['form']['total'])
	order.transaction_id = transaction_id

	if float(total) == float(order.get_cart_total):
		order.complete = True
		order.save()
		if order.shipping == True:
			ShippingAddress.objects.create(customer=customer,order=order,address=data['shipping']['address'],city=data['shipping']['city'],state=data['shipping']['state'],zipcode=data['shipping']['zipcode'],)
	return JsonResponse('Payment submitted..', safe=False)

store/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">

				<a  class="btn btn-outline-dark" href="{% url 'store' 0 %}">&#x2190; Continue Shopping</a>

				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
						<th><h5>Total:<strong> ${{order.get_cart_total|floatformat:2}}</strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'checkout' %}">Checkout</a>
						</th>
					</tr>
				</table>

			</div>

			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Color and size</strong></div>

					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>${{item.product.price}}</p></div>

					{%if user.is_authenticated%}
					<div style="flex:1"><p>{{item.color_size.color}} / {{item.color_size.size}}</p></div>
					 {%else%}
					 <div style="flex:1"><p>{{item.product.color}} / {{item.product.size}}</p></div>
 					{%endif%}

					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>
						<div class="quantity">
							<img data-product="{{item.product.id}}" data-color='{{item.color_size}}' data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">

							<img data-product="{{item.product.id}}" data-color='{{item.color_size}}' data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
						</div>
					</div>
					<div style="flex:1"><p>${{item.get_total}}</p></div>
				</div>
				{% endfor %}
				<input type="hidden" id="qty2" value=1>

			</div>
		</div>
	</div>
{% endblock content %}

store/templates/store/login.html
{%extends 'store/main.html'%}
{% load crispy_forms_tags %}

{%block content%}
<h1>Login</h1>
<!--the action is a post or get request sent to the same html page and inside the view rendering that html well detect if is a post or get and decide what to do  -->
<form class="site-form" action="{%url 'login' %}" method="post">
{%csrf_token%}
{{form|crispy}}
<!--get the next if it exits in the request and then save it to the hidden input -->
<!-- if it exits then send it back to the view and redirect the user to the page he was tryin to access-->
{%if request.GET.next%}
<input type="hidden" name="next" value="{{request.GET.next}}">
{%endif%}
<input type="submit" name="" value="Login">
</form>
{%endblock%}

store/templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Ecom</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
<!--css bootstrap	-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<!-- here we must place our css under bootstrap so we overwrite it if needed-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

	<script type="text/javascript">
		var user = '{{request.user}}'
		function getToken(name) {
		    var cookieValue = null;
		    if (document.cookie && document.cookie !== '') {
		        var cookies = document.cookie.split(';');
		        for (var i = 0; i < cookies.length; i++) {
		            var cookie = cookies[i].trim();
		            // Does this cookie string begin with the name we want?
		            if (cookie.substring(0, name.length + 1) === (name + '=')) {
		                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
		                break;
		            }
		        }
		    }
		    return cookieValue;
		}
		var csrftoken = getToken('csrftoken')

		//look in the document if there is a cookie named cart
		function getCookie(name) {
		    // Split cookie string and get all individual name=value pairs in an array
		    var cookieArr = document.cookie.split(";");

		    // Loop through the array elements
		    for(var i = 0; i < cookieArr.length; i++) {
		        var cookiePair = cookieArr[i].split("=");

		        /* Removing whitespace at the beginning of the cookie name
		        and compare it with the given string */
		        if(name == cookiePair[0].trim()) {
		            // Decode the cookie value and return
		            return decodeURIComponent(cookiePair[1]);
		        }
		    }

		    // Return null if not found
		    return null;
		}
		// the function above we r sure to take the same cookie and its content so we save the content of the cart for the user who is not logged in
		//see if the cookie with the name cookie exits by calling the fct
		var cart = JSON.parse(getCookie('cart'))
		// if not defined then creat one
		if (cart == undefined){
			//make a dict
			cart = {}
			console.log('Cart Created!', cart)
			//then add the dict to the document as a cookie to only our website by specifyin the domain and the path
			//and we stringify the dict to add it to the docuement
			//after when we process it with the fct js cart file we can make it jason object
			document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
		}
		// else print the content of the cookie
		console.log('Cart:', cart)
	</script>
</head>
<body>
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
							  <div class="container">
									<a class="navbar-brand" href="{% url 'store' 0 %}">Ecom</a>
									<ul class="navbar-nav mr-auto">
										<li class="nav-item active">
											<a class="nav-link" href="{% url 'store' 0 %}">Store <span class="sr-only">(current)</span></a>
										</li>
							    <div id="navbarContent" class="collapse navbar-collapse">
							      <ul class="navbar-nav mr-auto">
							        <!-- Level one dropdown -->
							        <li class="nav-item dropdown">
							          <a id="dropdownMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Categories</a>

												<ul aria-labelledby="dropdownMenu1" class="dropdown-menu border-0 shadow">
							            <!-- Level two dropdown-->
													{%for cat in categories%}
														<div class=" dropright">
							                    <a href="{% url 'store' cat.id %}" class="dropdown-item"  > {{cat}}{% if cat.subcategory_set.all.exists %} <i class="fa fa-angle-right"></i>	{%endif%}</a>
																	{% if cat.subcategory_set.all.exists %}
																	<div class="dropdown-menu">
																		{%for subcat in cat.subcategory_set.all%}
							                        <li><a class="dropdown-item"href="{% url 'store2' cat.id  subcat.id %}" >{{subcat}}</a></li>
																			{%endfor%}
							                    </div>
																	{%endif%}
							                </div>
															{%endfor%}
							          </ul>
							        </li>
							        <li class="nav-item"><a href="#" class="nav-link">About</a></li>
							        <li class="nav-item"><a href="#" class="nav-link">Services</a></li>
							        <li class="nav-item"><a href="#" class="nav-link">Contact</a></li>
							      </ul>
							    </div>
							  </div>

<!--
								<form class="form-inline search" >
											<input class="form-control mr-sm-2 " type="search" placeholder="Search" aria-label="Search">
											<input class="btn btn-success " type="submit" id="search"  value="search"></input>
								</form>
									-->


					 {%if user.is_authenticated%}
					 <div class="form-inline ">
									 <!--  when submitting it ll make a post request to the url we did link to the view in paths of the acc app-->
										 <form class="logout-link" action="{% url 'logout' %}" method="post">
											 <!-- when ever we make a post request alwas add this token-->
											 {%csrf_token%}
											 <input class="btn btn-warning " type="submit" id="search"  value="Logout"></input>
										 </form>
										 <a href="{% url 'cart' %}"><img  id="cart-icon" src="{% static 'images/cart.png' %}"></a>
		 								<p id="cart-total">{{cartItems}}</p>
					</div>
					 {%else%}
						 <div class="form-inline">
							 		<a href="{% url 'login' %}"class="btn btn-warning">Login</a>
									<a href="{%url 'signup'%}"class="btn btn-success">Signup</a>
									<a href="{% url 'cart' %}"><img  id="cart-icon" src="{% static 'images/cart.png' %}"></a>
									<p id="cart-total">{{cartItems}}</p>
							</div>
					 {%endif%}

		</nav>

<!--	havin bootstrap we can use tag name container to contain stuff	-->
     <div class="container">
            <br>
            {% block content %}
            {% endblock content %}
         </div>


	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>

</body>
</html>

store/templates/store/signup.html
{%extends 'store/main.html'%}
{% load crispy_forms_tags %}

{%block content%}
<h1>Signup</h1>

<!--the action is a post or get request sent to the same html page and inside the view rendering that html well detect if is a post or get and decide what to do  -->
<form class="site-form" action="{%url  'signup' %}" method="post">
{%csrf_token%}
{{form|crispy}}
<input type="submit" name="" value="Signup">
</form>
{%endblock%}

store/templates/store/slider.html
{%extends 'store/main.html'%}
{% load static %}
{%block content%}

	<style type="text/css">
		#content-wrapper{
			display: flex;
			flex-wrap: wrap;
			justify-content: center;
			align-items: center;
		}
		.column{
			width: 600px;
			padding: 10px;
		}
		#featured{
			max-width: 500px;
			max-height: 600px;
			object-fit: cover;
			cursor: pointer;
			border: 2px solid black;
		}
		.thumbnail{
			object-fit: cover;
			max-width: 180px;
			max-height: 100px;
			cursor: pointer;
			opacity: 0.5;
			margin: 5px;
			border: 2px solid black;

		}
		.active{
			opacity: 1;
		}
		#slide-wrapper{
			max-width: 500px;
			display: flex;
			min-height: 100px;
			align-items: center;
		}
		#slider{
			width: 440px;
			display: flex;
			flex-wrap: nowrap;
			overflow-x: hidden;
		}
		#slider{
			width: 440px;
			display: flex;
			flex-wrap: nowrap;
			overflow-x: auto;
		}
		#slider::-webkit-scrollbar {
		    width: 8px;
		}
		#slider::-webkit-scrollbar-track {
		    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
		}
		#slider::-webkit-scrollbar-thumb {
		  background-color: #dede2e;
		  outline: 1px solid slategrey;
		   border-radius: 100px;
		}
		.arrow{
			width: 30px;
			height: 30px;
			cursor: pointer;
			transition: .3s;
		}
		.arrow:hover{
			opacity: .5;
			width: 35px;
			height: 35px;
		}
	</style>
	<div class="row">
	<div class="col-lg-6">
			<img id="featured" src="{{product.imageURL}}">
			<div id="slide-wrapper">
				<img id="slideLeft" class="arrow" src="{% static 'images/arrow-left.png' %}">
				<div id="slider">
					{% for image in product.image_set.all%}
					<img class="thumbnail" src="{{image.imageURL}}">
					{% endfor %}
				</div>
				<img id="slideRight" class="arrow" src="{% static 'images/arrow-right.png' %}">
			</div>
      </div>
	<div class="col-lg-5">
			<h1>{{product}}</h1>
			<hr>
			<h3>${{product.price}}</h3>
			<p>{{product.description}}</p>
			<input value=1 type="number" id='qty'>
      <hr>
      <div class="select">

        <select  id="selectbox" >
          {% for colorsize in product.takencolorsize_set.all%}
          <option id="selectedcolorsize" value="{{colorsize.id}}">{{colorsize.color}}  {{colorsize.size}}</option>
          {%endfor%}
        </select>
      </div>

      <hr>

      <button data-product={{product.id}} data-action="add" class="btn btn-dark update-cart">Add to Cart</button>
</div>
</div>
	<script type="text/javascript">
			let thumbnails = document.getElementsByClassName('thumbnail')
			let activeImages = document.getElementsByClassName('active')
			for (var i=0; i < thumbnails.length; i++){
				thumbnails[i].addEventListener("click", function(){

					if (activeImages.length > 0){
						activeImages[0].classList.remove('active')
					}

					this.classList.add('active')
					document.getElementById('featured').src = this.src
				})
			}
			const buttonRight = document.getElementById('slideRight');
			const buttonLeft = document.getElementById('slideLeft');
			buttonRight.addEventListener('click', function(){
				document.getElementById('slider').scrollLeft += 180;
		    })
		    buttonLeft.addEventListener('click', function(){
		      document.getElementById('slider').scrollLeft -= 180;
		    })


	</script>

{%endblock%}

store/templates/store/store.html
{%extends 'store/main.html'%}
{% load static %}
{%block content%}


<div class="row">
	{%for product in products %}
		<div class="col-lg-4">
			<img class="thumbnail" src="{{product.imageURL}}">
			<div class="box-element product">
				<h6><strong>{{product.name}}</strong></h6>
				<hr>

				<a class="btn btn-outline-success" href="{% url 'slider' product.id%}">View</a>
				<h4 style="display: inline-block; float: right"><strong>${{product.price|floatformat:2}}</strong></h4>

			</div>
		</div>
		{%endfor%}
	</div>
{%endblock content%}